package net.sangeeth.jssdk.jsc;

public enum TokenType {
	DIRECTIVE,
	IDENTIFIER,
	KEYWORD,
	NUMERIC_LITERAL,
	REGEX_LITERAL,
	BOOLEAN_LITERAL,
	STRING_LITERAL,
	NULL_LITERAL,
	SEPARATOR,
	RELATIONAL_OPERATOR,
	ASSIGNMENT_OPERATOR,
	SHIFT_OPERATOR,
	UNARY_OPERATOR,
	BITWISE_OPERATOR,
	POSTFIX_OPERATOR,
	ARITHEMATIC_OPERATOR;
}
