package net.sangeeth.jssdk.jsp.el;

public enum TokenType {
	IDENTIFIER,
	KEYWORD,
	IMPLICIT_OBJECT,
	NUMERIC_LITERAL,
	BOOLEAN_LITERAL,
	STRING_LITERAL,
	NULL_LITERAL,
	SEPARATOR,
	UNARY_OPERATOR,
	BINARY_OPERATOR;
}
